name: Build and Upload Binaries
on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

jobs:
  build_and_upload:
    strategy:
      matrix:
        include:
          - os: windows-latest
            job_name: Windows
          - os: macOS-latest
            job_name: macOS
          - os: ubuntu-latest
            job_name: Linux
          - os: ubuntu-latest
            job_name: Linux (race)
            test_opts: "-race"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Build with build.go
        run: |
          go run build.go

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ matrix.job_name }}
          path: |
            # 假设二进制文件名为 restic 或 restic.exe
            restic*
